# Generated by Django 2.0.2 on 2021-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210701_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='NA', max_length=2000),
        ),
    ]
